### ISSUE TITLE
Color clues by list, priority, crawl etc.

### ISSUE THREAD

**Issue by daniel-goldstein** [daniel-goldstein/pawprints-mobile#10]
Either color or also just filter by. Not sure how you'd want to cross this with completed/uncompleted

**Comment by daniel-goldstein** [comment]
Just addressed this in the web app as independent filtering and seems to be ok, probably best to keep that consistent between platforms

**Comment by daniel-goldstein** [comment]
Don't know what priority means though. Probably not often enough to matter at this point

**Comment by joshspicer** [comment]
Does this mean you marking the pins on mobile for crawl/not crawl?

I think it would be cool for (uncompleted && crawl) clues to be a different color (if that's what we're prioritizing) 

@daniel-goldstein

**Comment by joshspicer** [comment]
And maybe a third option below specifically for crawls?

**Comment by daniel-goldstein** [comment]
How about red=incomplete normal clue, blue=completed clue (any), and different colors for each crawl incomplete clues. So if you see green, those pins are all in the same crawl and incomplete?

**Comment by daniel-goldstein** [comment]
I don't think it really matters on mobile to differentiate a completed clue that belonged to a crawl

**Comment by joshspicer** [comment]
That sounds good. That is a bit more complicated tho which is why i didn't suggest it. Do we have a mechanism to group clues into a specific crawl? Pretty sure the crawl flag is binary rn?

**Comment by daniel-goldstein** [comment]
They'll all have the same list ID. So Just as long as we have more colors than lists (pretty safe to say we won't need more than 10) we'll be fine

**Comment by joshspicer** [comment]
AH yes it is exactly one crawl per list.  Sweet
