### ISSUE TITLE
New storage location for photos

### ISSUE THREAD

**Issue by daniel-goldstein** [daniel-goldstein/pawprints-mobile#13]
Basically not firebase storage because that was crap to deal with and couldn't download all from the web console.

Google drive would be most easily accessible to the rest of the team but S3 or GCP would be fine if it's much easier.

**Comment by daniel-goldstein** [comment]
@joshspicer You want this?

**Comment by joshspicer** [comment]
yes!

**Comment by joshspicer** [comment]
I do think s3 would be easier to implement, but I recognize the usability benefits of google drive.  Investigating some ways to do that in RN with this

https://www.npmjs.com/package/react-native-google-drive-api-wrapper

**Comment by joshspicer** [comment]
Accomplished with #21
