### ISSUE TITLE
Actually publish the app

### ISSUE THREAD

**Issue by daniel-goldstein** [daniel-goldstein/pawprints-mobile#14]
Would be great to have a testflight or something that lets people with a link easily download and run the app. Last year I didn't think this far ahead and ended up just having people download expo and I signed in on all their devices. I'm scared of that not working this time around.

**Comment by joshspicer** [comment]
i have a dev account.  Can put it there if u want

**Comment by daniel-goldstein** [comment]
That'd be great, thanks!

**Comment by joshspicer** [comment]
did it (for iOS).
