### ISSUE TITLE
Get biking directions to selected pin

### ISSUE THREAD

**Issue by daniel-goldstein** [daniel-goldstein/pawprints-mobile#39]
Using google routes, draw a path leading bikers to a given pin. Important not to block their view of other clues, however, since detours for nearby clues is crucial for doing a thorough sweep of the area, especially since clues are constantly being added.

**Comment by daniel-goldstein** [comment]
This begs the more general question of whether larger routes should be developed that span, say, a region of boston or Cambridge. Manually by people at home base? Some approximation of TSP? Updated dynamically as clues are added? Who's to say.

**Comment by joshspicer** [comment]
excited for this

**Comment by daniel-goldstein** [comment]
Closing for archiving.
