### ISSUE TITLE
Add ability to upload photos from photo library

### ISSUE THREAD

**Issue by daniel-goldstein** [daniel-goldstein/pawprints-mobile#8]

**Comment by joshspicer** [comment]
I'm sure i'll accidentally add this in while setting up a new storage location

**Comment by joshspicer** [comment]
Also is nice to have photos in each player's photo libraries as a backup

**Comment by daniel-goldstein** [comment]
The app already saves to the user's camera roll in addition to uploading :smirk:

**Comment by daniel-goldstein** [comment]
@joshspicer I think this is the highest priority issue after any serious bugs
